### ISSUE TITLE
Remove NewBlockHashPacket/GetNewBlockPacket packets 

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1038]
## Is your feature request related to a problem? Please describe.

I think that in general we could get rid of whole "NewBlockHashPacket" packet. When I checked it is only send inside "onNewBlockVerified" to "in some way randomized" set of peers that do not have this block already(or at least we did not mark it as known fro them) and I am not sure what is the purpose of it ? 

If such peer received only block hash but does not have it locally it will instantly request our node to send him full block. If we dont send "NewBlockHashPacket"(why not send full block straight away ?), we could get rid also of "GetNewBlockPacket", which  is sent only if we received "NewBlockHashPacket", but we have not received full block yet. 

Seems to be like a lot of unnecessary code and complexity.... @justinsnapp @mfrankovi you might know ?

**Comment by MatusKysel** [comment]
I think this should be closed as it is saving quite a lot of network bandwidth
