### ISSUE TITLE
Refactor db structures to support fast syncing

### ISSUE THREAD

**Issue by mfrankovi** [Taraxa-project/taraxa-node#1057]
Currently when a node serves only one period for syncing, this is performed from the DB point of view:

Query Columns::period_pbft_block to retrieve pbft block hash from period_pbft_block
Query Columns::pbft_blocks by pbft block hash to retrieve the full pbft block
Query Columns::cert_votes to retrieve cert votes for pbft block
Query Columns::dag_finalized_blocks to retrieve list of dag blocks hashes for the pbft block
Multi Query Columns::dag_blocks to retrieve all the dag blocks by hashes - currently in testnet this is a multiquery matching about 60 dag block hashes to dag blocks
Multi Query Columns::transactions to retrieve all the transactions - currently in testnet this is a multiquery matching about 2000 transactions hashes to transactions

This is very inefficient. Specially for transactions but the same applies for dag blocks as well. Also there is no point in having two different data in two columns under the same unique key.

All of the data above should be kept in a single rocksdb column. So one RLP serialized data for a period should consis of pbft block, cert votes, dag blocks and transactions. A syncing request for a period would just be:
1. Pull RLP for a period with a single query and send it out.

The only downside in this approach is case when there is a need to pull specific DAG block or transaction. Node it self will never require the dag block or transaction that is already executed. 
The only use case for this is explorer where someone could ask for a specific transaction or a dag block. For this it will require two queries instead of one it needs now. But I do not see any use case where someone would do a huge query for a lot of specific transactions. Any such request should be a malicious one.

Transaction and dag blocks that are not executed yet will be kept in the current Columns::dag_blocks and Columns::transactions but once they are executed they should be removed from these columns

Test performed to check the effectiveness of this approach compared with the current implementation. On the current testnet of about 30GB of data and current node implementation for 25 pbft blocks it takes about 2500ms in average to pull the transactions from db. To query the same transactions stored per period it takes only 20ms.

**Comment by MatusKysel** [comment]
There is also I think we should add and that's something like small cache for this, so when someone want to just sync up latest ~50 pbft blocks or so we do not need to touch DB
