### ISSUE TITLE
Missing logs

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1072]
### Description
During debugging of new tarcap threadpool, I noticed that multiple logs are simply skipped for some reason. Did not really investigate it further but seems like our logging does not work properly in all scenarios.

### Steps to reproduce

1. Copy paste [this log](https://github.com/Taraxa-project/taraxa-node/blob/feature/issue-911/packets-priority_queue-threadpool/src/network/tarcap/threadpool/tarcap_thread_pool.cpp#L98) uder existing one and just use std::cout instead  
2. Run FullNodeTest.sync_two_nodes1
3. Analyze logs - there is not our boost log for every std::cout log (not even delayed ones)

**Comment by MatusKysel** [comment]
you are not passing `node_addr` to NodeStats, `const addr_t &node_addr = {}` should be never used

**Comment by JakubFornadel** [comment]
> you are not passing `node_addr` to NodeStats, `const addr_t &node_addr = {}` should be never used

cool, thanks...
