### ISSUE TITLE
Sending Votes Bundle

### ISSUE THREAD

**Issue by gaoqi8649** [Taraxa-project/taraxa-node#1158]
## Is your feature request related to a problem? Please describe.
Votes need to be grouped, and will be able to send in a bundle

 

## Describe the solution you'd like.

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by JakubFornadel** [comment]
@gaoqi8649 was this developed ? As far as I remeber it was not right ?

**Comment by gaoqi8649** [comment]
> @gaoqi8649 was this developed ? As far as I remeber it was not right ?

Since we have binominal distribution for weighted vote, we don't need it anymore.
