### ISSUE TITLE
Do NOT keep genesis in dag_blocks

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1244]
### Description
We should remove Dag block from `dag_blocks` column, because causing a lot of problems

**Comment by JakubFornadel** [comment]
@MatusKysel is this still relevant ?

**Comment by MatusKysel** [comment]
yes, we are not removing it from DB and this column is only for non-finalized blocks

**Comment by JakubFornadel** [comment]
closing issue as linked PR is already merged
