### ISSUE TITLE
Strict gossip rules - validation in handlers 

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1323]
## Is your feature request related to a problem? Please describe.

We are accepting any data(that can be parsed from rlp) and saving it into the unverified_queue. 
## Describe the solution you'd like.

Verify block as soon as received inside packet handler and push only verified blocks into the verified queue.  Whole threadpool verifying blocks can be delete, unverified_queue can be deleted, ....

**Comment by gaoqi8649** [comment]
The current design that use 4 threads for verify DAG blocks in unverified_queue. If move DAG blocks verification into packet handler, I think that will effect network packet handler performance

**Comment by JakubFornadel** [comment]
> The current design that use 4 threads for verify DAG blocks in unverified_queue. If move DAG blocks verification into packet handler, I think that will effect network packet handler performance

packets handlers are inside network threadpool as well. Big advantage of such design is that you dont need other trheadpools like you just mentioned anymore...
