### ISSUE TITLE
New networks for testing/developing

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1410]
## Is your feature request related to a problem? Please describe.
Currently we have really messy networks and it is getting difficult to maintain:
**mainnet** -> easy (master branch)
**testnet** -> pure mess (testnet branch) but has nothing in common with develop and has lot of hardforks that we will never use on mainnet
**devnet** -> I guess almost nobody is using this network, everyone is using PRnet for they features, witch is much better because we do not interfere with our changes between each other

## Describe the solution you'd like.
This is my proposal to have our development easier:
**mainnet** -> no change
**testnet** -> this is where we have community, so this is best environment to test things. I suggest to dump our current testnet and deploy here regularly our develop branch (e.g. every Friday community needs to update/reset their nodes -> they are paid for it). No hardforks here that are not part of mainnet or that will be part of mainnet. This way we can test our code on more nodes and catch bug easier.
**devnet** -> we should get rid of this one. Everyone can use PRnets for their features/bugfixes ...
**stablenet** -> 1:1 copy of mainnet where hardforks will happened some time before (like a week before mainnet), so we can see what will happened to mainnet network. We do not need to have community here, but we can advertise mainnet runners to test their configs before mainnet.

PS: naming is open to suggestions, we do not need to keep names of network like that

**Comment by JakubFornadel** [comment]
I agree. Few arguments: 

- it is not maintainable to have different hardforks for mainnet and testnet... It would be very messy to use this approach in code.
- we could have basically only master, devnet and user's branches used for PR's... Testnet branch could be deleted
- I would say lets deploy new version every Monday(not Friday) - we would increase version on develop branch, create a tag and deploy new images. 
- there will be only hardforks that have to be deployed on mainnet in codebase, everything else is solved by reset !

**Comment by kstdl** [comment]
Main concern about testnet resets was that users wont do it. But I guess we dont need all of  them, so it sounds reasonable to me
