### ISSUE TITLE
Implement staking contract

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1415]
# Task Title

Task: Implement staking contract

## Task Description

Implement staking contract that will store information about all validators & delegators:
- their staking/delegation balances
- rewards 
- withdrawal requests
- contract must be upgradeable
- ....

## Epic Parent

[Feature: Implement rewards distribution](https://github.com/Taraxa-project/taraxa-node/issues/1413).

## Discussion
Hi guys, so we could have a call yoday at 1pm to brainstorm the precompiled the dpos contract, what do you think ? 

Few important notes/ideas/questions to be discussed:
1. Existing contract lacks some functionality(not talking about rewards & slashing now) - for example when we build some
   Staking UI, user will login through his wallet(e.g. metamask) and we need to provide 2 contract read calls:
   	- get_all_validators - so there will be a list of all validators(their current total stake/commission/website/etc...) that user can check and delegate to
   	- get_delegator_validators - these are all validators that logged user already delegated to. We will display his delegated stake to each one/rewards/etc... and user can click
   	  claim_rewards or undelegate for each validator he delegated to
   For this purpose we must provide "iterable maps" in our contract and not just basic maps
   
2. My original idea was to have contract data in memory as well as in storage - when someone delegates to a validator, we would save it in memory and also to storage. Thanks to this approach
   we would serve data for read calls from memory without needing to read storgae, which would be much more efficient - this is not really possible with delay being implemented as "loading outdated(delayed) storage for contract address"
   as we do right now - I was thinking about some other way, but did not find anything
Also think about rewards calculations - lets say we have 20 validators and each one has 100 delegators - thats 2k delegators, which we would probably have to get one by one from storage in case we want to use delayed data also for rewards calculations. On the other hand we could use current data and get it from memory, which would be also instant...
   
3. Another difference with new contract vs the old one is that we will provide solidity interface, which will enable third-party contracts to read our contract: 
   - Should these data be delayed too or not ? I dont know
   - Will we have 2 interfaces - 1 for node (needed for consensus stuff like checking staking balance, etc..), which will be delayed and one for contract, which will not be delayed ? This could
     be probably imepmented in a way that we would have 1 interface(functions implementations), but when called from node, we would load outdated contract storage and for solidity calls we would use
     updated/current contract storage ?
   - This is pretty important to decide as it might significantly affects the code

4. How to save iterable maps into the storage ?
Requirements are:
- this structure must be iterable and also provide the ability of constant access by key -> value mapping.

When we look for example at "Delegators" map in "ValidatorInfo struct" from example below, it could be saved in storage as
(validator_addr & delagtor_addr) -> DelegatorInfo

Now how do we get the list of all delegators for each validator(we need this for calculating rewards) in the most efficient way ?
- there must some extra struct(e.g. array) that will save array of delegators addresses for each validator, e.g. 
(validator_addr) -> []delegator_addr

but we probably also need to have a constant access to this array in case some delegator undelegates tokens from a validator and we want to delete him - we would need some additional map
that would tell us that his address in "[]delegator_addr" array is save at position 95 for example and we will delete him through swap from that array. In solidity I did implement it like this:

```
struct IterableMap {
	// map of indexes to the list array
	// indexes are shifted +1 compared to the real indexes of this list, because 0 means non-existing element
	mapping(address => uint256) list_index;

	// list of addresses
	address[] list;        
}

// Adds acc from the map
function insertAcc(IterableMap storage map, address acc) internal {
	map.list.push(acc);
	// indexes are stored + 1   
	map.list_index[acc] = map.list.length;
}

// Removes acc from the map
function removeAcc(IterableMap storage map, address acc) internal {
	uint256 index = map.list_index[acc];
	require(index > 0 && index <= map.list.length, "RemoveAcc invalid index");

	// Move an last element of array into the vacated key slot.
	uint256 foundIndex = index - 1;
	uint256 lastIndex  = map.list.length - 1;

	map.list_index[map.list[lastIndex]] = foundIndex + 1;
	map.list[foundIndex] = map.list[lastIndex];
	map.list.pop();

	// Deletes element
	delete map.list_index[acc];
}
```

We will probably need something similar also here ? This needs to be resolved somehow

This is my proposed golang memory layout of contract data that also needs to be saved in storage (TODO: implement some sort of iterable map that will be saved in storage)

```
// Validator basic info
type ValidatorInfo struct {
	// TotalStake == sum of all delegated tokens to the validator
	TotalStake *big.Int

	// Commission
	Commission *big.Int

	// Rewards accumulated from delegators rewards based on commission
	CommissionRewards *big.Int

	// Short description
	// TODO: optional - maybe we dont want this ?
	Description string

	// Validator's website url
	// TODO: optional - maybe we dont want this ?
	Endpoint string

	// List of validator's delegators
	Delegators map[common.Address]*DelegatorInfo
}

type DelegatorInfo struct {
	// Num of delegated tokens == delegator's stake
	Stake *big.Int

	// UnlockedStake == unlocked(undelegated) tokens that can be withdrawn now
	// TODO: in case we will send unlocked tokens to the delegator's balance automatically, we dont need this field
	UnlockedStake *big.Int

	// Accumulated rewards
	Rewards *big.Int

	// Undelegate request
	// TODO: rethink implementation of undelegations
	UndelegateRequests []*UndelegateRequestInfo
}

type UndelegateRequestInfo struct {
	// Num of tokens that delegator wants to undelegate
	Amount *big.Int

	// Block number when this unstake request can be confirmed(act block num + locking period)
	EligibleBlockNum *big.Int
}

// Delegator's validators info
type DelegatorValidators struct {
	// List of validators addresses that delegator delegated to
	// Note: info about delegator's stake/reward, etc... is saved in ValidatorDelegators struct
	Validators map[common.Address]bool // instead of set
}

type Contract struct {
	Storage StorageWrapper
	Abi     abi.ABI

	// Validadors basic info, e.g. total stake, commission, etc...
	ValidatorsInfo map[common.Address]*ValidatorInfo

	// Delegators list of their validators -> key = delegator address
	DelegatorsValidators map[common.Address]*DelegatorValidators
	
	// ...
}
```

**Comment by MatusKysel** [comment]
https://github.com/Taraxa-project/taraxa-evm/pull/48
