### ISSUE TITLE
Minimum system requirement

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1451]
## Task Description

Achieve sub-linear resource vs. block production to ensure fair consensus - i.e., not a hardware arms race

**Comment by MatusKysel** [comment]
Tested with https://github.com/MatusKysel/taraxa-utils/blob/master/transaction_generator.py

So minimum requirements for consensus node are
```
2 CPUs
2GB of RAM
100 Mbit/s connection
SSD -> size deepens on chain size
```

Recommended
```
4 CPUs
4GB of RAM
500 Mbit/s connection
SSD -> size deepens on chain size
```
