### ISSUE TITLE
Fix PBFT rebroadcast soft votes for current round in Mainnet

### ISSUE THREAD

**Issue by gaoqi8649** [Taraxa-project/taraxa-node#1491]
## Task Description

Same issue https://github.com/Taraxa-project/taraxa-node/issues/1488, need fix in Mainnet

**Comment by JakubFornadel** [comment]
@gaoqi8649 we are not using flow where you create separate PR for develop/testnet and master branches... So these issue probably should not have been created

**Comment by gaoqi8649** [comment]
> 

Emm..., If only create issue and have a fix have merged to develop, then the issue will be closed. How to record the issue if have been fix in Mainnet/Testnet when fix have merged into develop?

**Comment by gaoqi8649** [comment]
> @gaoqi8649 we are not using flow where you create separate PR for develop/testnet and master branches... So these issue probably should not have been created

Emm..., If only create issue and have a fix have merged to develop, then the issue will be closed. How to record the issue if have been fix in Mainnet/Testnet when fix have merged into develop?
