### ISSUE TITLE
Support 2 protocol versions at the same time

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1541]
# Support 2 protocol versions at the same time

## Some capabilities with different packets

We have functionality that allows us to have few capabilities. Different versions of nodes could have different capabilities sets. If we are having more than one capability that means that we support a few network protocol versions. To communicate one with another nodes should support the same protocol version. That means that peer with newer version should have old capability. Additional difficulties is that we have modifications in that code, so it maybe we will have some issues with that functionality 

1. Create some BaseCapability class. It should have basic functionality that we can override in classes that we would inherit from it. We should be able to override methods and register different packet handlers. I think BaseCapability shouldn't register any PacketHandler, we should do it in classes that inherits from it. Because it should be the main difference between different versions of capabilities. Code should be also organized and grouped in dirs by capability version
2. On peer connection we would be comparing supported capabilities of our node and connecting peer. If we can't found match between these nodes capabilities then we are dropping a connection.
3. In new versions if we are not supporting some old capability we should just remove it with related code(packet handlers, ...)

## Additional improvements

1. Avoid numerous passing of different managers and db into other classes by creating node interface class
2. Organize and maybe remove part of classes and interfaces related to capability, because for some reason we added some of them(for example SessionCapability)

**Comment by JakubFornadel** [comment]
- Do you have also some proposal how to solve node versioning, which basically does not allow us to increase MAJOR nor MINOR version at all ? 
- maybe you could also check how ethereum solves this, I think they release new version every 2 weeks so they must solve this somehow
- It sort of feels like we should support 2 different capabilities(if the versions differ in capabilities) only for the latest 2 node versions (not protocol versions) as that should be enough time for everyone to update, if they dont - they will be forced to as their node wont be able to exchange some info

**Comment by kstdl** [comment]
@JakubFornadel the idea is to not check node version at all. If two nodes have capabilities with same version, then one can connect to another. 
For example one is older supports [6,7] version and other one is newer and supports [7,8]. So they can communicate through capability with version 7

Ethereum checks only protocol version and supports only current and previous versions. If node has protocol version 4 it will allow to connect only 3 and higher. We can do kind of the same thing, but I think checking of capabilities versions is kind of the same thing and it should be enough

**Comment by JakubFornadel** [comment]
hmm yeah just one note to consider: if we would also check node version, we could enforce people to regularly update. Otherwise lets say we will create release every other week but for a long time there is no hardfork, nor protocol version change. Users would not need to update at all. On the other hand if we would allow only 2 latest node versions to connect, we would force them to update...
