### ISSUE TITLE
CryptoTest.leader_selection failing

### ISSUE THREAD

**Issue by kstdl** [Taraxa-project/taraxa-node#1554]
CryptoTest.leader_selection sometimes failing failing on develop 
https://app.circleci.com/pipelines/github/Taraxa-project/taraxa-node/5064/workflows/fff0db1a-9393-45ad-b96c-03fdf1b23647/jobs/5491

**Comment by JakubFornadel** [comment]
needs to be revisited and finetuned so the test never fails...
