### ISSUE TITLE
Revisit static code analysis (cppcheck + other tools)

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1571]
This is a part of any security audit that we are going to go through in upcoming weeks so we should revisit our setup, fine tune it if possible and maybe use also some additional tools to make sure we are good

**Comment by MatusKysel** [comment]
@JakubFornadel regarding the issue you described with cppcheck, I found the bug in cppcheck and reported https://sourceforge.net/p/cppcheck/discussion/development/thread/5c82c947a3/ let's what they think about that

**Comment by MatusKysel** [comment]
I have also run clang static analyzer with following result

**Comment by MatusKysel** [comment]
I have also run clang static analyzer with following result
```
scan-build: Analysis run complete.
scan-build: Removing directory '/tmp/scan-build-2022-03-16-144130-74295-1' because it contains no reports.
scan-build: No bugs found.
```
so I believe `cpp-check` with all the warnings on is just enough

**Comment by JakubFornadel** [comment]
I am reopening this issue. I did run the static analysis properly and found more than 200 reports, most of them are valid but not critical...

**Comment by JakubFornadel** [comment]
> I have also run clang static analyzer with following result
> 
> ```
> scan-build: Analysis run complete.
> scan-build: Removing directory '/tmp/scan-build-2022-03-16-144130-74295-1' because it contains no reports.
> scan-build: No bugs found.
> ```
> 
> so I believe `cpp-check` with all the warnings on is just enough

I am not sure how you run the analysis but we have tons of "bugs" - most of them not really critical but still valid

**Comment by MatusKysel** [comment]
> > I have also run clang static analyzer with following result
> > ```
> > scan-build: Analysis run complete.
> > scan-build: Removing directory '/tmp/scan-build-2022-03-16-144130-74295-1' because it contains no reports.
> > scan-build: No bugs found.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so I believe `cpp-check` with all the warnings on is just enough
> 
> I am not sure how you run the analysis but we have tons of "bugs" - most of them not really critical but still valid

like this `scan-build -o /tmp/myhtmldir make -j4 taraxad`

**Comment by JakubFornadel** [comment]
> > > I have also run clang static analyzer with following result
> > > ```
> > > scan-build: Analysis run complete.
> > > scan-build: Removing directory '/tmp/scan-build-2022-03-16-144130-74295-1' because it contains no reports.
> > > scan-build: No bugs found.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > so I believe `cpp-check` with all the warnings on is just enough
> > 
> > 
> > I am not sure how you run the analysis but we have tons of "bugs" - most of them not really critical but still valid
> 
> like this `scan-build -o /tmp/myhtmldir make -j4 taraxad`

So I am using CodeChecker, which is basically replacement of scan-build. I guess it is more sophisticated as it found multiple bugs compared to zero using scan build...

**Comment by MatusKysel** [comment]
> > > > I have also run clang static analyzer with following result
> > > > ```
> > > > scan-build: Analysis run complete.
> > > > scan-build: Removing directory '/tmp/scan-build-2022-03-16-144130-74295-1' because it contains no reports.
> > > > scan-build: No bugs found.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > so I believe `cpp-check` with all the warnings on is just enough
> > > 
> > > 
> > > I am not sure how you run the analysis but we have tons of "bugs" - most of them not really critical but still valid
> > 
> > 
> > like this `scan-build -o /tmp/myhtmldir make -j4 taraxad`
> 
> So I am using CodeChecker, which is basically replacement of scan-build. I guess it is more sophisticated as it found multiple bugs compared to zero using scan build...

hmm, it looks like it is just extension that combines scan-build and clang-tidy, so what you found are clang-tidy issues
