### ISSUE TITLE
Priting usless info on malicious peer

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1598]
In cases like this PacketData info is irrelevant, maybe for the debug

```
0x00007fd5a8fc9640 415cf514… TRANSACTION_PH [2022-03-02 14:26:58.884168] ERROR: Exception caught during packet processing: PacketProcessingException -> MaliciousPeer: Transaction 56c844653d17bff236a84f856c0d3819572ef63777ffb2cb6869a41c5b7e0482 validation failed: insufficient balance. 
PacketData: {
        "from_node_id" : "39f0ba2434d3fc74873a22558b1678e2daa6567e2451b2927b6aa43b979ecbbfbbd0baac1455b5235b9e15e426c1501c2a08d73d4e6eb881d742e659ae52e453",
        "id" : 2495,
        "priority" : 1,
        "receive_time" : "2022-03-02 14:26:58 node local time",
        "rlp_items_count" : 8,
        "rlp_size" : 0,
        "type" : "TransactionPacket"
}
```

**Comment by JakubFornadel** [comment]
I would say it is pretty relevant if we are talking about the cases of peer being labeled as malicious so you can see based on which packet it happened. + it does not really hurt anything. This particular error should not happen almost at all, it is happening on our tests and I fixed it already. Let's work on things that matter and leave this as it is

**Comment by MatusKysel** [comment]
> It seems pretty relevant if we are talking about the cases of peer being labeled as malicious so you can see based on which packet it happened + it does not really hurt anything. This particular error should not happen almost at all, it is happening on our tests and I fixed it already. I would leave this as it is

This is only relevant when peer sends wrong RLP I guess as you do not know anything else about the packet. In cases like this it is irrelevant and it is spamming our logs. But peer id should be logged

**Comment by MatusKysel** [comment]
fixed by https://github.com/Taraxa-project/taraxa-node/commit/78d5a7a50bd852fdbc8e976a1e103cc6c1a0a6de
