### ISSUE TITLE
Include all important data fields into the genesis hash

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1602]
Notes: 
- merge this task few days/weeks before mainnet launch & mainnet candidate reset

Currently create genesis hash only from `dag_genesis_block`, which is not good. When calculating the hash, we should definitely use also other data, e.g.:

- final_chain.genesis_balances
- probably also many other params - TO BE DISCUSSED

Notes:
These params are not used at all (can be deleted):
- network_simulated_delay
- network_udp_port
- network_is_boot_node -> it is used but I guess it does not make sense as we have different binary for boot node now
- network_bandwidth -> seems we dont need this
- replay_protection_service -> we commented this code out. Questionable if we should keep this or not - I incline more towards not having it in config
- gas_price -> what is this for ?
- run_count_votes -> seems like misuage of config. It hsould not be in config. Qi is using this for debug messages....
- test_params -> what are these for ? If we are using it for something serious, it should not be called test_params...
-

**Comment by gaoqi8649** [comment]
Should also include all PBFT params. Nodes running at the same network must have same PBFT params
