### ISSUE TITLE
Clean up "Lazy" class

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1657]
``

## Task Description

Clean up [`Lazy` class](https://github.com/Taraxa-project/taraxa-node/blob/develop/libraries/common/include/common/lazy.hpp#L18):

- get rid of `new` and `delete`
- whole class is complicated
- do we even need it ?

**Comment by MatusKysel** [comment]
Maybe we do not need it, but we should measure if removing it does not increase test time or something
