### ISSUE TITLE
Instability of node_sync2 test

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1675]
NetworkTest.node_sync2 is failing from time to time. We should look at it, but it is probably caused by https://github.com/Taraxa-project/taraxa-node/issues/1639

```
0x0000000307f17000 973ecb1c… DAG_SYNC_PH [2022-04-05 17:42:27.742529] ERROR: Exception caught during packet processing: PacketProcessingException -> MaliciousPeer: DagBlock transaction 05d03651339f5cfa30790a7be5aac4552f373688b79503085bdfe0a470eb557b validation failed: nonce too low .PacketData: {"from_node_id":"7b1fcf0ec1078320117b96e9e9ad9032c06d030cf4024a598347a4623a14a421d4f030cf25ef368ab394a45e920e14b57a259a09c41767dd50d1da27b627412a","id":12,"priority":1,"receive_time":"2022-04-05 17:42:27 node local time","rlp_items_count":30,"rlp_size":0,"type":"DagSyncPacket"}
[  FAILED  ] NetworkTest.node_sync2
```

**Comment by gaoqi8649** [comment]
qigao@Qis-MacBook-Pro cmake-Debug % ./bin/network_test --gtest_filter=NetworkTest.node_sync2
Note: Google Test filter = NetworkTest.node_sync2
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from NetworkTest
[ RUN      ] NetworkTest.node_sync2
0x0000000112d39600 de2b1203… FULLND [2022-04-19 18:19:01.214572] SILENT: Node public key: 7b1fcf0ec1078320117b96e9e9ad9032c06d030cf4024a598347a4623a14a421d4f030cf25ef368ab394a45e920e14b57a259a09c41767dd50d1da27b627412a
Node address: de2b1203d72d3549ee2f733b00b2789414c7cea5
Node VRF public key: d05dc12c1df1edc9f3367fba550b7971fc2de6c5998d8784051c5be69abc9644
0x0000000112d39600 de2b1203… FULLND [2022-04-19 18:19:01.214572] SILENT: Node public key: 7b1fcf0ec1078320117b96e9e9ad9032c06d030cf4024a598347a4623a14a421d4f030cf25ef368ab394a45e920e14b57a259a09c41767dd50d1da27b627412a
Node address: de2b1203d72d3549ee2f733b00b2789414c7cea5
Node VRF public key: d05dc12c1df1edc9f3367fba550b7971fc2de6c5998d8784051c5be69abc9644
0x000070000207a000 de2b1203… VOTE_MGR [2022-04-19 18:19:01.362335] SILENT: Retrieve verified votes from DB
0x000070000207a000 de2b1203… VOTE_MGR [2022-04-19 18:19:01.362335] SILENT: Retrieve verified votes from DB
0x0000000112d39600 973ecb1c… FULLND [2022-04-19 18:19:01.522826] SILENT: Node public key: 2dc3306fc215049c867975c2dcf8743ea76e4d1aca654ba44775bb2561970bef0ac470f779cf7549b04b756f7e0befce3063a8b1ebf241911a6ab57e41ed2650
Node address: 973ecb1c08c8eb5a7eaa0d3fd3aab7924f2838b0
Node VRF public key: 931f5e7db07c9969e438db7e287eabbaaca49ca414f5f3a402ea6997ade40081
0x0000000112d39600 973ecb1c… FULLND [2022-04-19 18:19:01.522826] SILENT: Node public key: 2dc3306fc215049c867975c2dcf8743ea76e4d1aca654ba44775bb2561970bef0ac470f779cf7549b04b756f7e0befce3063a8b1ebf241911a6ab57e41ed2650
Node address: 973ecb1c08c8eb5a7eaa0d3fd3aab7924f2838b0
Node VRF public key: 931f5e7db07c9969e438db7e287eabbaaca49ca414f5f3a402ea6997ade40081
0x0000700002ece000 973ecb1c… VOTE_MGR [2022-04-19 18:19:01.654358] SILENT: Retrieve verified votes from DB
0x0000700002ece000 973ecb1c… VOTE_MGR [2022-04-19 18:19:01.654358] SILENT: Retrieve verified votes from DB
0x0000700002ece000 973ecb1c… VOTE_MGR [2022-04-19 18:19:01.654358] SILENT: Retrieve verified votes from DB
0x00007000034f2000 973ecb1c… DAG_SYNC_PH [2022-04-19 18:19:03.904537] SILENT: Restarting syncing PBFT from peer ##7b1fcf0e…, peer PBFT chain size 1, own PBFT chain synced at period 0
0x00007000034f2000 973ecb1c… DAG_SYNC_PH [2022-04-19 18:19:03.904537] SILENT: Restarting syncing PBFT from peer ##7b1fcf0e…, peer PBFT chain size 1, own PBFT chain synced at period 0
0x00007000034f2000 973ecb1c… DAG_SYNC_PH [2022-04-19 18:19:03.904537] SILENT: Restarting syncing PBFT from peer ##7b1fcf0e…, peer PBFT chain size 1, own PBFT chain synced at period 0
0x000070000346f000 973ecb1c… DAG_SYNC_PH [2022-04-19 18:19:05.029906] ERROR: Exception caught during packet processing: PacketProcessingException -> MaliciousPeer: DagBlock transaction 8bcb1377e4126867f769e83ac06395785ab1ca6915895e3063eae97313d57f44 validation failed: nonce too low .PacketData: {"from_node_id":"7b1fcf0ec1078320117b96e9e9ad9032c06d030cf4024a598347a4623a14a421d4f030cf25ef368ab394a45e920e14b57a259a09c41767dd50d1da27b627412a","id":13,"priority":1,"receive_time":"2022-04-19 18:19:05 node local time","rlp_items_count":33,"rlp_size":0,"type":"DagSyncPacket"}
0x000070000346f000 973ecb1c… DAG_SYNC_PH [2022-04-19 18:19:05.029906] ERROR: Exception caught during packet processing: PacketProcessingException -> MaliciousPeer: DagBlock transaction 8bcb1377e4126867f769e83ac06395785ab1ca6915895e3063eae97313d57f44 validation failed: nonce too low .PacketData: {"from_node_id":"7b1fcf0ec1078320117b96e9e9ad9032c06d030cf4024a598347a4623a14a421d4f030cf25ef368ab394a45e920e14b57a259a09c41767dd50d1da27b627412a","id":13,"priority":1,"receive_time":"2022-04-19 18:19:05 node local time","rlp_items_count":33,"rlp_size":0,"type":"DagSyncPacket"}
0x000070000346f000 973ecb1c… DAG_SYNC_PH [2022-04-19 18:19:05.029906] ERROR: Exception caught during packet processing: PacketProcessingException -> MaliciousPeer: DagBlock transaction 8bcb1377e4126867f769e83ac06395785ab1ca6915895e3063eae97313d57f44 validation failed: nonce too low .PacketData: {"from_node_id":"7b1fcf0ec1078320117b96e9e9ad9032c06d030cf4024a598347a4623a14a421d4f030cf25ef368ab394a45e920e14b57a259a09c41767dd50d1da27b627412a","id":13,"priority":1,"receive_time":"2022-04-19 18:19:05 node local time","rlp_items_count":33,"rlp_size":0,"type":"DagSyncPacket"}
/Users/qigao/Taraxa/taraxa-node/tests/network_test.cpp:1202: Failure
Expected equality of these values:
  node1->getDagManager()->getNumVerticesInDag().first
    Which is: 13
  node2->getDagManager()->getNumVerticesInDag().first
    Which is: 3
/Users/qigao/Taraxa/taraxa-node/tests/network_test.cpp:1204: Failure
Expected equality of these values:
  node1->getDagManager()->getNumEdgesInDag().first
    Which is: 13
  node2->getDagManager()->getNumEdgesInDag().first
    Which is: 2
/Users/qigao/Taraxa/taraxa-node/tests/network_test.cpp:1205: Failure
Value of: wait({50s, 300ms}, [&](auto& ctx) { if (node1->getDagManager()->getNumVerticesInDag().first != node2->getDagManager()->getNumVerticesInDag().first) { if (ctx.fail(); !ctx.is_last_attempt) { return; } switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("node1->getDagManager()->getNumVerticesInDag().first", "node2->getDagManager()->getNumVerticesInDag().first", node1->getDagManager()->getNumVerticesInDag().first, node2->getDagManager()->getNumVerticesInDag().first))) ; else ::testing::internal::AssertHelper(::testing::TestPartResult::kNonFatalFailure, "/Users/qigao/Taraxa/taraxa-node/tests/network_test.cpp", 1202, gtest_ar.failure_message()) = ::testing::Message(); } if (node1->getDagManager()->getNumEdgesInDag().first != node2->getDagManager()->getNumEdgesInDag().first) { if (ctx.fail(); !ctx.is_last_attempt) { return; } switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("node1->getDagManager()->getNumEdgesInDag().first", "node2->getDagManager()->getNumEdgesInDag().first", node1->getDagManager()->getNumEdgesInDag().first, node2->getDagManager()->getNumEdgesInDag().first))) ; else ::testing::internal::AssertHelper(::testing::TestPartResult::kNonFatalFailure, "/Users/qigao/Taraxa/taraxa-node/tests/network_test.cpp", 1204, gtest_ar.failure_message()) = ::testing::Message(); } })
  Actual: false
Expected: true
[  FAILED  ] NetworkTest.node_sync2 (50339 ms)
[----------] 1 test from NetworkTest (50339 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (50339 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NetworkTest.node_sync2

 1 FAILED TEST
