### ISSUE TITLE
NetworkTest.node_sync2 sometimes failing

### ISSUE THREAD

**Issue by kstdl** [Taraxa-project/taraxa-node#1702]
Met this in CI on PR that is just adding one more logging configuration, so I believe that fail is not related to changes and can face it in develop branch also 
https://app.circleci.com/pipelines/github/Taraxa-project/taraxa-node/5622/workflows/710f57b0-34ad-4a9b-b39a-512268f76772/jobs/6100

**Comment by gaoqi8649** [comment]
Duplicate with https://github.com/Taraxa-project/taraxa-node/issues/1675
