### ISSUE TITLE
full_node_test sometimes hangs in CI

### ISSUE THREAD

**Issue by kstdl** [Taraxa-project/taraxa-node#1768]
full_node_test sometimes hangs in CI. https://app.circleci.com/pipelines/github/Taraxa-project/taraxa-node/5919/workflows/2fd9b5ec-5533-45cb-834f-0dcf9432f7d6/jobs/6431

**Comment by MatusKysel** [comment]
https://github.com/Taraxa-project/taraxa-node/pull/1805
