### ISSUE TITLE
Leave only one of network_id and chain_id

### ISSUE THREAD

**Issue by kstdl** [Taraxa-project/taraxa-node#1812]
Right now we have network_id in network config and chain_id in chain config. But it should be the same thing, or it should be totally separated if not. 
Right now we [have this](https://github.com/Taraxa-project/taraxa-node/blob/develop/libraries/config/src/config.cpp#L257), but we can have situation when network_id will be changed in the config, but not chain id and it could mess something.

**Comment by MatusKysel** [comment]
https://besu.hyperledger.org/en/stable/Concepts/NetworkID-And-ChainID/ I think we took it from eth, that have both of this values
