### ISSUE TITLE
Transaction gossip overload

### ISSUE THREAD

**Issue by mfrankovi** [Taraxa-project/taraxa-node#1869]
Transaction gossip depends on the known transactions cache for each peer. If transactions pool grows larger that known transactions cache same transactions will be sent over and over again spamming entire network.

Quick fix on teestnet was increasing the cache. Smarter solution is needed.

**Comment by MatusKysel** [comment]
Transaction pool improvements proposal:
- introducing limit per account (e.g. one account can only have 30% of total size of the pool) 
- introducing expiration time limit (e.g. transaction older then 3h hours, should be removed)
- known transactions per peer object will depend on pool size (e.g. if pool size is 30k then known cache could be like 110% so 33k)
