### ISSUE TITLE
Differentiate between standard & reward vote through flag

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1880]
There is ton of occasions when we wrongly identify standard vote as a reward vote, which leads to validation fails, etc...

The reason is that we identify vote as reward vote based on vote pbft round:
`if (vote_round < current_pbft_round) {  // reward vote`

That is problem because some out of sync nodes might be sending us standard votes with older round and we identify it as reward votes... These votes could be dropped right away if we knew they are supposed to be standard votes...

### Solution

Add flag into the vote, which will explicitly say "this is reward vote"

To reproduce this problem, run:
`PbftManagerTest.check_get_eligible_vote_count  `

**Comment by justinsnapp** [comment]
@JakubFornadel , I would have naively thought a standard vote could be used as a reward vote?   Remind me to ask for more insight into this in a meeting (unless its easy to just answer as a comment here.)
