### ISSUE TITLE
Mainnet assert

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1888]
Assert reported by community:

mainnet_node_1 exited with code 134
node_1        | 0x00007f881c19c300 FULLND [2022-07-25 07:48:53.099916] SILENT: Node public key: 04dbe8cc1fc8a69def99f89a432089df67a10909d95854b22cd43b7dd7c02717bb4ec38a2b1e82cd31d257107d794f592343ac1d54a8bcd1101e6a77ae75d1e1
node_1        | Node address: 50e455793e2c8eced55539668f7d4671d417fb76
node_1        | Node VRF public key: 7f5c148cd0df3342f74100ebf7f50906816e142339d30faeb6cda49e39413802
node_1        | taraxad: /opt/taraxa/libraries/core_libs/consensus/src/final_chain/final_chain.cpp:69: taraxa::final_chain::FinalChainImpl::FinalChainImpl(const shared_ptr<taraxa::DB> &, const taraxa::final_chain::Config &, const taraxa::addr_t &): Assertion `state_db_descriptor.blk_num == 0' failed.
node_1        | Aborted (core dumped)

**Comment by MatusKysel** [comment]
So after thorough investigation it looks like user tried to disabled snapshots and somehow managed to corrupt his this DB. As we do not have any snapshot available at this moment, re-sync was only option to recover from this
