### ISSUE TITLE
Use 0x54 prefix for chain IDs

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1904]
## Task Description

Change our chain IDs as some tools identify our chains as orig. ethereum ones (ropsten, ....)

mainnet - 0x5401
testnet - 0x5402
devnet - 0x5403

I am not so sure about command line options using 1,2,3 and then transforming it into the hex 0x5401, 0x5402, 0x5404... As chain ID can be configured in config and then we just hardcode the transformation in the code, if someone runs his own local net and uses some other chain id in config, e.g. 0x5301 or 0x01 this hardcoded transformation wont work...

Make this change only after https://github.com/Taraxa-project/taraxa-node/pull/1894 is merged

**Comment by justinsnapp** [comment]
I think for the "transform" it's only for ids we want to exclude so 1,2,3 and others?    Could also make it so you pass in "T1", etc if people prefer that approach.  Or else pass in named networks like mainnet, testnet, devnet.

**Comment by justinsnapp** [comment]
I guess we can have different arguments.  like pass in network (name), Or network Id

**Comment by MatusKysel** [comment]
So ascii `T` is 84, let's have it like this in decimal:

```
841 - mainnet
842 - testnet
843 - devnet
```
