### ISSUE TITLE
Reward votes syncing/gossiping issue with multiple rounds

### ISSUE THREAD

**Issue by mfrankovi** [Taraxa-project/taraxa-node#1933]
@mfrankovi I dont think this will work. If I push block at round 1 and save cert votes from this round as reward votes and others push this block at round 2 - they will save cert votes from round 2 so they dont have cert votes from round 1. Then when I try to regossip my reward votes(cert votes from round 1) it is ignored as these votes are marked as already known for others...

_Originally posted by @JakubFornadel in https://github.com/Taraxa-project/taraxa-node/pull/1930#pullrequestreview-1069620116_

**Comment by JakubFornadel** [comment]
In this PR https://github.com/Taraxa-project/taraxa-node/pull/2273, if we are stuck and broadcastVotes with regossip = true is invoked, reward votes are sent without any filter
