### ISSUE TITLE
Next voting issue on devnet

### ISSUE THREAD

**Issue by mfrankovi** [Taraxa-project/taraxa-node#1943]
On high tps load devnet can get stuck for a long time even after most of the transactions packet are processed where network is not advancing rounds. Network gets into a state where half of the network is next voting NULL block and another half is voting for some specific block which on some of the nodes is already cert voted and pushed into chain.

This is an example of such logs for round 5 for all the nodes on the devnet:
	Line 3: /root/.taraxa/logs/Taraxa_N1_08152022_113756_00153.log:0x00007f9f39feb640 9588f645… PBFT_MGR [2022-08-15 12:17:22.229542] INFO: Next votes 62 voting #db56f4cd… for round 161268, at step 5
	Line 39: /root/.taraxa/logs/Taraxa_N1_08152022_113756_00153.log:0x00007f9f39feb640 9588f645… PBFT_MGR [2022-08-15 12:17:40.349455] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268

	Line 9: /root/.taraxa/logs/Taraxa_N1_08152022_115934_00153.log:0x00007f50f17f2640 b48da366… PBFT_MGR [2022-08-15 12:17:22.258154] INFO: Next votes 63 voting NULL BLOCK for round 161268, at step 5
	Line 45: /root/.taraxa/logs/Taraxa_N1_08152022_115934_00153.log:0x00007f50f17f2640 b48da366… PBFT_MGR [2022-08-15 12:17:44.761279] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161269

	Line 65: /root/.taraxa/logs/Taraxa_N1_08152022_113635_00151.log:0x00007f63667f4640 614c85fa… PBFT_MGR [2022-08-15 12:17:22.825652] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	Line 29: /root/.taraxa/logs/Taraxa_N1_08152022_113635_00151.log:0x00007f63667f4640 614c85fa… PBFT_MGR [2022-08-15 12:17:22.962838] INFO: Next votes 47 voting NULL BLOCK for round 161268, at step 5

	Line 35: /root/.taraxa/logs/Taraxa_N1_08152022_113441_00153.log:0x00007f48b57ea640 eff3dd2b… PBFT_MGR [2022-08-15 12:17:22.152688] INFO: Next votes 59 voting #db56f4cd… for round 161268, at step 5
	Line 71: /root/.taraxa/logs/Taraxa_N1_08152022_113441_00153.log:0x00007f48b57ea640 eff3dd2b… PBFT_MGR [2022-08-15 12:17:39.483571] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	

	Line 61: /root/.taraxa/logs/Taraxa_N1_08152022_114923_00151.log:0x00007fbed67f4640 64c171b9… PBFT_MGR [2022-08-15 12:17:22.178712] INFO: Next votes 65 voting #db56f4cd… for round 161268, at step 5
	Line 97: /root/.taraxa/logs/Taraxa_N1_08152022_114923_00151.log:0x00007fbed67f4640 64c171b9… PBFT_MGR [2022-08-15 12:17:41.150522] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	

	Line 117: /root/.taraxa/logs/Taraxa_N1_08152022_113441_00152.log:0x00007f9b53ff7640 4546f088… PBFT_MGR [2022-08-15 12:17:22.858711] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	Line 81: /root/.taraxa/logs/Taraxa_N1_08152022_113441_00152.log:0x00007f9b53ff7640 4546f088… PBFT_MGR [2022-08-15 12:17:23.116260] INFO: Next votes 51 voting NULL BLOCK for round 161268, at step 5
	

	Line 123: /root/.taraxa/logs/Taraxa_N1_08152022_113449_00135.log:0x00007fe39f7f6640 8ca04264… PBFT_MGR [2022-08-15 12:17:22.814788] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	Line 87: /root/.taraxa/logs/Taraxa_N1_08152022_113449_00135.log:0x00007fe39f7f6640 8ca04264… PBFT_MGR [2022-08-15 12:17:23.402744] INFO: Next votes 62 voting NULL BLOCK for round 161268, at step 5
	

	Line 143: /root/.taraxa/logs/Taraxa_N1_08152022_113640_00151.log:0x00007f1c8c7f8640 635d3831… PBFT_MGR [2022-08-15 12:17:22.914613] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	Line 107: /root/.taraxa/logs/Taraxa_N1_08152022_113640_00151.log:0x00007f1c8c7f8640 635d3831… PBFT_MGR [2022-08-15 12:17:23.062201] INFO: Next votes 63 voting NULL BLOCK for round 161268, at step 5
	

	Line 113: /root/.taraxa/logs/Taraxa_N1_08152022_120139_00151.log:0x00007ff06cff1640 43af7103… PBFT_MGR [2022-08-15 12:17:22.156103] INFO: Next votes 54 voting #db56f4cd… for round 161268, at step 5
	Line 149: /root/.taraxa/logs/Taraxa_N1_08152022_120139_00151.log:0x00007ff06cff1640 43af7103… PBFT_MGR [2022-08-15 12:17:46.736261] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161270
	

	Line 133: /root/.taraxa/logs/Taraxa_N1_08152022_120046_00151.log:0x00007f2bb5ff3640 5354adf5… PBFT_MGR [2022-08-15 12:17:22.084113] INFO: Next votes 62 voting NULL BLOCK for round 161268, at step 5
	Line 169: /root/.taraxa/logs/Taraxa_N1_08152022_120046_00151.log:0x00007f2bb5ff3640 5354adf5… PBFT_MGR [2022-08-15 12:17:52.783963] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161270
	

	Line 139: /root/.taraxa/logs/Taraxa_N1_08152022_113444_00153.log:0x00007fb00b7f6640 1473a6c1… PBFT_MGR [2022-08-15 12:17:22.104904] INFO: Next votes 50 voting #db56f4cd… for round 161268, at step 5
	Line 175: /root/.taraxa/logs/Taraxa_N1_08152022_113444_00153.log:0x00007fb00b7f6640 1473a6c1… PBFT_MGR [2022-08-15 12:17:38.585106] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	

	Line 159: /root/.taraxa/logs/Taraxa_N1_08152022_113306_00159.log:0x00007f34bdff3640 71bdcbec… PBFT_MGR [2022-08-15 12:17:22.070293] INFO: Next votes 62 voting #db56f4cd… for round 161268, at step 5
	Line 195: /root/.taraxa/logs/Taraxa_N1_08152022_113306_00159.log:0x00007f34bdff3640 71bdcbec… PBFT_MGR [2022-08-15 12:17:39.612286] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	

	Line 165: /root/.taraxa/logs/Taraxa_N1_08152022_115536_00158.log:0x00007f316cff1640 ac24bc60… PBFT_MGR [2022-08-15 12:17:22.088458] INFO: Next votes 55 voting #db56f4cd… for round 161268, at step 5
	Line 201: /root/.taraxa/logs/Taraxa_N1_08152022_115536_00158.log:0x00007f316cff1640 ac24bc60… PBFT_MGR [2022-08-15 12:17:42.407596] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161269
	

	Line 185: /root/.taraxa/logs/Taraxa_N1_08152022_120204_00158.log:0x00007faf797ea640 780fe8b2… PBFT_MGR [2022-08-15 12:17:22.112068] INFO: Next votes 59 voting NULL BLOCK for round 161268, at step 5
	Line 221: /root/.taraxa/logs/Taraxa_N1_08152022_120204_00158.log:0x00007faf797ea640 780fe8b2… PBFT_MGR [2022-08-15 12:20:30.637045] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161270
	

	Line 191: /root/.taraxa/logs/Taraxa_N1_08152022_114231_00158.log:0x00007fb3d9ffb640 56e0de69… PBFT_MGR [2022-08-15 12:17:22.139668] INFO: Next votes 55 voting #db56f4cd… for round 161268, at step 5
	Line 227: /root/.taraxa/logs/Taraxa_N1_08152022_114231_00158.log:0x00007fb3d9ffb640 56e0de69… PBFT_MGR [2022-08-15 12:17:38.098032] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	

	Line 247: /root/.taraxa/logs/Taraxa_N1_08152022_114437_00157.log:0x00007fadc3ff7640 e543a20d… PBFT_MGR [2022-08-15 12:17:23.058862] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	Line 211: /root/.taraxa/logs/Taraxa_N1_08152022_114437_00157.log:0x00007fadc3ff7640 e543a20d… PBFT_MGR [2022-08-15 12:17:23.071195] INFO: Next votes 54 voting NULL BLOCK for round 161268, at step 5
	

	Line 253: /root/.taraxa/logs/Taraxa_N1_08152022_114818_00158.log:0x00007f2421ff3640 211a5ec3… PBFT_MGR [2022-08-15 12:17:22.938994] INFO: Pushed new PBFT block #db56f4cd… into chain. Period: 160702, round: 161268
	Line 217: /root/.taraxa/logs/Taraxa_N1_08152022_114818_00158.log:0x00007f2421ff3640 211a5ec3… PBFT_MGR [2022-08-15 12:17:22.956168] INFO: Next votes 57 voting NULL BLOCK for round 161268, at step 5

**Comment by JakubFornadel** [comment]
since this issue was created we did major changed in pbft, closing this issue as it is not relevant to the current code
