### ISSUE TITLE
Send and process VotesSyncPacket only with votes from one step

### ISSUE THREAD

**Issue by kstdl** [Taraxa-project/taraxa-node#1964]
I think right now we have issues in design of NextVotesManager and maybe using VotesSyncPacket not properly because we could receive bundle with different steps. We should count on this conditions later when we would be changing(removing?) NextVotesManager.  This will help us to detect inappropriate packets and deal with maliciousness

**Comment by JakubFornadel** [comment]
Yes when we are syncing next votes, we send both 2t+1 next votes for null block hash as well as some specific block hash and these could have different steps... It can be easily changed but not sure if we really need it ?

Other problem I just noticed is that we dont validate period & round for next votes syncing, which we should. Will add it to this PR https://github.com/Taraxa-project/taraxa-node/pull/2273
