### ISSUE TITLE
Rare heap corruption in the p2p test

### ISSUE THREAD

**Issue by 02p01r** [Taraxa-project/taraxa-node#695]
In https://github.com/Taraxa-project/taraxa-node/pull/656 there's a very rare error that I saw in `p2p_test`. The error reads:
```
malloc(): mismatching next->prev_size (unsorted)
Signal: SIGABRT (Aborted)
```
Once I saw it, i tried running that test on a loop, and catching the crash in a debugger. After 30 min to 2 hours of repeatedly running the test, the error shows itself, always in different spots. For example, I saw it here https://github.com/Taraxa-project/taraxa-aleth/blob/050ddac66c4e76563f125ebc04afab942bd602b4/libp2p/RLPxHandshake.cpp#L140
or here https://github.com/Taraxa-project/taraxa-node/blob/8f08f907ff906cf1c9661e5d42bac0ce64e3dbe4/src/util/thread_pool.cpp#L42

Googling tells me that this is a kind a kind of error that could be set up in one place as a "time bomb", and reveal itself completely unexpectedly in the other place after a time. Apparently, the heap gets messed somewhere, and then on any subsequent allocation there's some probability to get this error.  

Debugging such an error postmortem seems hardly possible. Instead, I suggest using memory sanitizers or similar tools to eliminate any possible heap problems.

**Comment by 02p01r** [comment]
@justinsnapp why did you close it?

**Comment by MatusKysel** [comment]
fix by https://github.com/Taraxa-project/taraxa-aleth/pull/23
