### ISSUE TITLE
Transactions(+ statutes) db storage optimization

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#793]
### Current simplified flow when received broadcasted transactions:

- transaction is received, saved into the local unverified queue and database (+ tx status "unverified" is saved in db as well)
- once it is verified in separate thread, it is moved from local unverified queue to the verified queue and tx status in db is set to "verified", or "invalid" in case verification did not pass
- once it is included in dag block, tx status is set to "in_block" 

#### Cons
- a lot of database handling (locking) due to transaction status separate storage

### Proposed new flow when received broadcasted transactions:

- transaction is received, saved into the local unverified queue
- once it is verified in separate thread, it is moved from local unverified queue to the verified queue and transaction is also saved in db -> this means that only valid verified tx is saved in db

#### Pros
- we get rid of transaction status handling, which is redundant information because "unverified/verified" status we know based on in which queue is tx currently stored + only verified txs are stored in db as well. "in_block" status is used only as a synchronization mechanism during proposing new dag block so we dont include txs that we received in other dag block in the meantime -> this can be easily solved without involving rocksdb 
- as we store in db only verified transactions, we can store also verified signature (public key) and during execution of pbft block we dont need to verify these signatures again as we do now 
- some smaller optimizations would be also possible in dag blocks handling....

**Comment by justinsnapp** [comment]
@JakubFornadel  how do you tell if a transaction has or hasn't been packed into a block once its in the db?  You say this is easily solved without involving rocksdb, but it does need to be in the db no?  Or else after a node restart how does one know what transactions are verified but not yet placed into a block?

**Comment by JakubFornadel** [comment]
@JakubFornadel when tx is packed into block, it is removed from local verified_txs queue so if the tx is saved in db and not in verified_queue -> it was packet in some block... Actually the only place in code where we want to know if the tx was included in block is during proposing. When node is running normaly the argument from above is applied. Once the node restarts your local queues are empty so there are no txs to propose a new block from -> node syncs and wait for a little while until it receives new txs and in such case those are going to be for sure new txs
