### ISSUE TITLE
Restrict branches access

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#821]
I want to propose new changes. I created set of rules(settings) for different branches in taraxa-node github repo. There is different settings for:
- master, 
- develop, 
- feature/*, 
- release/*, 
- hotfix/*
- **/** (all other branches)
 
I would also propose to give everyone in here "Write" access and only 1 person with "Admin" access in both EU and US timezones. Based on the new roles and branches settings it would pretty easy and straightforward to keep our repo clean, structured and without any hacks like direct commits to develop or master -> can't think of any situation when this should be needed... 

What we can achieve by this:
- only admins can do any sort of hacks like direct commits to protected branches, etc... (but they really should not even if they can....)
- master will have restricted write access - we will specify set of people who can write (even merge PR's) to master - let's say admins
- people with write access can create and merge PR's to develop but only those PR's that have 2 approvals and all checks passed, no direct commits will be technically possible for them 
- it wont be possible(easily) even for admins to merge PR's without at least 2 approvals and all checks passed - I believe we should really start doing proper reviews instead of merging stuff without approvals. This way people will be enforced to ask other team member to make a review and give their PR approval... 

I understand the fact that this should be strictly required once we have some real stable version in master as our testnet is using images from master and at the moment we are simply hot-fixing things... But cannot we restart testnet with provided custom image tag so we dont need to merge all these "fix tries" into master as we did  few days ago ? @rattrap @agrebin that is question for you guys I guess...

**Comment by JakubFornadel** [comment]
@Taraxa-project/ledger please have a look at this.

**Comment by justinsnapp** [comment]
Agree we should do this.

**Comment by JakubFornadel** [comment]
access restricted, repo settings updated...
