### ISSUE TITLE
Logs default behaviour - warning + error logs enabled for all channels 

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#822]
## Is your feature request related to a problem? Please describe.

At the moment we dont see error and warning logs if nor explicitly enabled by channel config...

## Describe the solution you'd like.

Enable error and warning logs for all channels as default behaviour. If channel config is provided, it would override default behaviour...

**Comment by MatusKysel** [comment]
My suggestion is use current configuration but with different behavior:

``` 
"logging": {
    "configurations": [
      {
        "name": "standard",
        "on": true,
        "verbosity": "ERROR",
        "channels": [
          {
            "name": "SUMMARY",
            "verbosity": "INFO"
          }
        ],
```
let's use `verbosity` as default one for all channels and then we can use channels configuration to override it for specific channel.
