### ISSUE TITLE
chore(sandbox): compile issue

### ISSUE THREAD

**Issue by gaoqi8649** [Taraxa-project/taraxa-node#828]
### Description
CMakeLists allowed to create sandbox for taraxa node
https://github.com/Taraxa-project/taraxa-node/blob/develop/CMakeLists.txt#L195

under local directory could create CMakeLists_ext.cmake:
add_executable(sandbox local/sandbox.cpp)
target_link_libraries(
        sandbox
        app_base
        gtest
)

and create sandbox.cpp do help function for taraxa node. For example:
#include <atomic>
#include <functional>
#include <iostream>
#include <thread>
#include "../tests/util_test/util.hpp"
using namespace taraxa;
using namespace std;

int main() {  
  auto node_cfgs = core_tests::make_node_cfgs(5);
  auto nodes = core_tests::launch_nodes(node_cfgs);
  for (uint i = 0;; ++i) {
    auto node_index = i % nodes.size();
    auto &node = nodes[node_index];
    cout << "Node " << node_index << " num blocks: " << node->getFinalChain()->last_block_number() << endl;
    node->getTransactionManager()->insertTransaction(
        Transaction(i, 1, 0, 0, {}, nodes[0]->getSecretKey(), node->getAddress()), true);
        this_thread::sleep_for(500ms);
    }
  return 0;
} 

##### Node version

**Use docker command to find node image version:**

> docker images --format '{{.ID}}' 'taraxa/taraxa-node:latest' 

##### CPU, memory, disk details. 

**NOTE: In many cases log files are also useful to include. Since these files may be large, a Taraxa developer may request them later. These files may include public addresses that you're participating with. If that is a concern please be sure to scrub that data.**

### Steps to reproduce

1.
2.

### Actual behaviour
The sanbox cannot compile anymore, compile errors:

ld: library not found for -lgtest
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/sandbox] Error 1
make[1]: *** [CMakeFiles/sandbox.dir/all] Error 2
make: *** [all] Error 2

**Comment by JakubFornadel** [comment]
@gaoqi8649 Whatever it is on your local folder, it is your local code, which we dont see of course and it is intended for your personal testing/hacks/etc.... 

It has nothing to do with taraxa-node code so it is not really something that you should create issue for. And btw just by quick look it is obvious that you have problems with gtest linking. If you check for example cmake for our tests you would find out that gtest is linked from conan now and not as local library. Try to use  

target_link_libraries(
sandbox
app_base
CONAN_PKG::gtest
)

**Comment by JakubFornadel** [comment]
Closing this issue as nonrelevant
