### ISSUE TITLE
feat(pbft): Improve PBFT blocks and previous round next votes syncing

### ISSUE THREAD

**Issue by gaoqi8649** [Taraxa-project/taraxa-node#851]
## Is your feature request related to a problem? Please describe.

PBFT will sync blocks and previous round next votes in every 100 steps 

## Describe the solution you'd like.

Should be at exponential backoff. Like every 2 steps, 4 steps, 8 steps, etc

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by JakubFornadel** [comment]
@gaoqi8649 is this still relevant ?

**Comment by gaoqi8649** [comment]
> @gaoqi8649 is this still relevant ?

Fixed already

**Comment by gaoqi8649** [comment]
Fixed in https://github.com/Taraxa-project/taraxa-node/pull/1282
