### ISSUE TITLE
Improve vote counting performance when have lots of steps in a round

### ISSUE THREAD

**Issue by justinsnapp** [Taraxa-project/taraxa-node#852]
## Describe the solution you'd like.

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by JakubFornadel** [comment]
@justinsnapp @gaoqi8649 is this issue still relevant ? It is pretty old and many changes were introduced since this was created.

**Comment by gaoqi8649** [comment]
> @justinsnapp @gaoqi8649 is this issue still relevant ? It is pretty old and many changes were introduced since this was created.

Binomial distribution for weighted vote fixed the issue
