### ISSUE TITLE
Extraneous guards and checks within taraxa capability should be cleaned up

### ISSUE THREAD

**Issue by justinsnapp** [Taraxa-project/taraxa-node#958]
## Is your feature request related to a problem? Please describe.

See comments on PR #941  for example:

`  if ((!peer) || (dag_mgr_ && !peer->received_initial_status_ && packet_type != StatusPacket)) `

In general we have a lot of checks in code just because of tests, which should not be there or at least it should be somehow checked only if we are running tests through some #ifdef TESTS or something like that.

**Comment by JakubFornadel** [comment]
Merged into the https://github.com/Taraxa-project/taraxa-node/issues/854 as it is related to the same topic
